### ISSUE TITLE
[bug]: Charlie Waist Ease slider doesn't do anything

### ISSUE THREAD

**Issue by jpmunic** [freesewing/freesewing#6391]
### What seems to be the problem? 🤔

For values between 0% and 1.8%, the waist ease slider doesn't change the pattern.

https://github.com/freesewing/freesewing/assets/13474972/7674f7d8-1181-44d2-8d15-910395afe97c

### Design / Plugin / Package 🧐

designs/charlie

### Additional context

measurements:
<img width="303" alt="Screenshot 2024-03-17 at 7 09 13 PM" src="https://github.com/freesewing/freesewing/assets/13474972/0b563281-2e61-4b16-8ced-39e71171d186">

**Comment by BenJamesBen** [comment]
I am not able to reproduce this bug on freesewing.org using the given measurements.

With `paperless` mode enabled, I see that the dimensions of the Front part's waist area change when the Waist Ease slider is used. Specifically, I see the top halves of the Front waistline seam increase from 10.4 cm and 7.9 cm  to 10.41 cm and 7.91 cm when Waist Ease is increased from 0.0% to 0.1%. Similar dimension changes are seen when sliding the setting across the range from 0% to 1.8% and beyond.

Waist Ease 0.0%:
![Screenshot 2024-03-18 at 9 38 39 AM](https://github.com/freesewing/freesewing/assets/109869956/bcf3769a-1e05-4eef-8685-7debb736cae9)

Waist Ease 0.1%:
![Screenshot 2024-03-18 at 9 38 49 AM](https://github.com/freesewing/freesewing/assets/109869956/f24d840e-273f-411f-95f3-ff0bd42c5912)

```yaml
measurements:
  crossSeam: 840
  crossSeamFront: 370
  knee: 350
  seat: 960
  seatBack: 460
  waist: 830
  waistBack: 400
  waistToFloor: 1080
  waistToKnee: 590
  waistToHips: 120
  waistToSeat: 220
  waistToUpperLeg: 310
units: metric
only:
  - charlie.front
paperless: true
options:
  waistEase: 0
```
